{% set version = "0.6.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xlsx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/xlsx_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/xlsx/xlsx_{{ version }}.tar.gz
  sha256: 378c5ed475a3d7631ea1ea13e0a69d619c1a52260922abda42818752dbb32107

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rjava
    - r-xlsxjars
  run:
    - r-base
    - r-rjava
    - r-xlsxjars

test:
  commands:
    - $R -e "library('xlsx')"           # [not win]
    - "\"%R%\" -e \"library('xlsx')\""  # [win]

about:
  home: https://github.com/dragua/rexcel, http://groups.google.com/group/R-package-xlsx
  license: GPL-3
  summary: Provide R functions to read/write/format Excel 2007 and Excel 97/2000/XP/2003 file formats.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: xlsx
# Type: Package
# Title: Read, Write, Format Excel 2007 and Excel 97/2000/XP/2003 Files
# Version: 0.6.1
# Date: 2018-06-07
# Imports: rJava, xlsxjars, grDevices, utils
# LazyLoad: yes
# Author: Adrian A. Dragulescu, Cole Arendt
# Maintainer: Adrian A. Dragulescu <adrian.dragulescu@gmail.com>
# Description: Provide R functions to read/write/format Excel 2007 and Excel 97/2000/XP/2003 file formats.
# License: GPL-3
# URL: https://github.com/dragua/rexcel, http://groups.google.com/group/R-package-xlsx
# BugReports: https://github.com/dragua/rexcel/issues
# SystemRequirements: java (>= 1.6)
# NeedsCompilation: no
# Packaged: 2018-06-11 00:21:04 UTC; adrian
# Repository: CRAN
# Date/Publication: 2018-06-11 05:50:21 UTC
