{% set version = "0.6.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xlsx
  version: {{ version|replace("-", "_") }}

source:
  fn: xlsx_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/xlsx_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/xlsx/xlsx_{{ version }}.tar.gz
  sha256: a580bd16b5477c1c185bf681c12c1ffff4088089f97b6a37997913d93ec5a8b4

build:
  number: 0
  # r-rjava and r-xlsxjars not available under win
  skip: true  # [win]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-rjava
    - r-xlsxjars

  run:
    - r-base
    - r-rjava
    - r-xlsxjars

test:
  commands:
    - $R -e "library('xlsx')"  # [not win]
    - "\"%R%\" -e \"library('xlsx')\""  # [win]

about:
  home: http://code.google.com/p/rexcel/, http://groups.google.com/group/R-package-xlsx
  license: GPL-3
  summary: Provide R functions to read/write/format Excel 2007 and Excel 97/2000/XP/2003 file
    formats.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
