appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: heP2BeW6tNfuNYqEIdYZt/de1kWTkP7hSamNhQk2B5rLVxu7pCMkWe2KEzC4K3UXWMEuycaXYL1psFFmq9yZcwodw3Ovn0lP7eOHQ6NzDQ6iNCvrDa/fg4SD6XcQCopqe6NA7LcNT2MLr+7H8n9JwJpbZxYrMtzmqGnkeo+WJ6o7bpjb4iCOOjIl6X1hnBWRNNmnp5gcE4Oz3qg/TfmZb2a+UZoKYUklzZQJVYOBy/Djc6LBCiiVHvGHBrNyXw1wS4FXPDq/bR46Olm/kEuoztWCa4cLkXX4DtPCEbvki5Bd3r4a/GkcEkJd6jTZHksbxB80n3zC75ZDIi+TlmivjBa3Ax+ly3CfuhkyMK6yQ8njrx/4jJO70mtwMhOjiPpCgM5WnDwjCRtVUGJXGCBczhl8+u6oHDfZW8tJOM66eYu0msZfvl9iSQgmedihD+ZYzdI7agA8wvvz/+1p3fpo3vaDKjpMxTRG7/LWHptYiui22WLVg0+Uo87PgOJNN9LwVsgFRtX3mw8wU7x0BH77sbSBjLrNxBRoMP4iwC5RXp5WSvxuTfcGDIkvK2Sah0q8Y/StjfnETWQJuJCQfHriYUs9wfnpniVdFqk7h8MqKDsfvaEQ9VSJ3Ll5vmTHbz1kVNkfm3g1TcKYLU+Zn9+l3YL4R/NOIrZrkCSI0WrGUcA=}
bot:
  automerge: true
conda_forge_output_validation: true
